**Student ID: 2408861**

**Student Name: Prachi Rajbanshi**

**6CS012 | Worksheet 0 | Feb 24, 2026**


In [ ]:
# 4.1 Exercise on Functions
# Task 1

def convert_units(value, conversion_type):

  #Conversion Constants
  M_TO_FT = 3.28084
  KG_TO_LBS = 2.20462
  L_TO_GAL = 0.26417

  if conversion_type == 1:
    return value * M_TO_FT, "Feet"
  elif conversion_type == 2:
    return value / M_TO_FT, "Meters"
  elif conversion_type == 3:
    return value * KG_TO_LBS, "Pounds"
  elif conversion_type == 4:
    return value / KG_TO_LBS, "Kilograms"
  elif conversion_type == 5:
    return value * L_TO_GAL, "Gallons"
  elif conversion_type == 6:
    return value / L_TO_GAL, "Liters"
  else:
    return None

def main():
  print("=====Multi-Unit Converter=====")
  print("==============================")
  print("Select a conversion: ")
  print("1: Meters to Feet | 2: Feet to Meters")
  print("3: Kilograms to Pounds | 4: Pounds to Kilograms")
  print("5: Liters to Gallons | 6: Gallons to Liters")

  try:
    choice = int(input("\nEnter the number of your choice (1-6): "))

    if choice not in range(1, 7):
      print("Error: Please select a valid option between 1 to 6")
      return

    val = float(input("Enter the value to convert: "))

    result, unit = convert_units(val, choice)

    if result is not None:
      print(f"\nResult: {val} converts to {result} {unit}")

  except ValueError:
    print("Invalid Input: Please enter numeric values only")

main()




=====Multi-Unit Converter=====
Select a conversion: 
1: Meters to Feet | 2: Feet to Meters
3: Kilograms to Pounds | 4: Pounds to Kilograms
5: Liters to Gallons | 6: Gallons to Liters

Enter the number of your choice (1-6): 1
Enter the value to convert: 2

Result: 2.0 converts to 6.56168 Feet


In [ ]:
# 4.1 Exercise on Functions
# Task 2

def get_sum(num):
  return sum(num)

def get_avg(num):
  return sum(num) / len(num) if num else 0

def get_max(num):
  return max(num)

def get_min(num):
  return min(num)

def main():
  print("===== Math Operator =====")

  try:
    user_input = input("Enter a list of numbers seperated by spaces: ")

    num_list = [float(x) for x in user_input.split()]

    if not num_list:
      print("Error: The list cannot be empty")
      return

    print("\nChoose an operation")
    print("1. Sum | 2. Average | 3. Maximum | 4. Minimum")
    choice = input("Enter your choice (1-4): ")

    if choice == '1':
      print(f"Sum: {get_sum(num_list)}")
    elif choice == '2':
      print(f"Average: {get_avg(num_list)}")
    elif choice == '3':
      print(f"Maximum: {get_max(num_list)}")
    elif choice == '4':
      print(f"Minimum: {get_min(num_list)}")
    else:
      print("Error: Invalid choice.")

  except ValueError:
    print("Error: Please ensure you enter numbers seperated by spaces")
  except Exception as e:
    print(f"An error occurred: {e}")

main()


===== Math Operator =====
Enter a list of numbers seperated by spaces: 2 3 4 5 6

Choose an operation
1. Sum | 2. Average | 3. Maximum | 4. Minimum
Enter your choice (1-4): 2
Average: 4.0


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 1 - Extract Every Other Element

def extract_every_other(lst):
  return lst[::2]

original_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(original_list)
print(f"Original: {original_list}")
print(f"Extracted: {result}")


Original: [1, 2, 3, 4, 5, 6]
Extracted: [1, 3, 5]


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 2 - SLice a Subset

def get_sublist(lst, start, end):
  return lst[start:end+1]

original_list = [1, 2, 3, 4, 5, 6]
result = get_sublist(original_list, 2, 4)
print(f"Original: {original_list}")
print(f"Extracted: {result}")


Original: [1, 2, 3, 4, 5, 6]
Extracted: [3, 4, 5]


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 3 - Reverse a List Using Slicing

def reverse_list(lst):
  return lst[::-1]

original_list = [1, 2, 3, 4, 5, 6]
reversed_result = reverse_list(original_list)

print(f"Original: {original_list}")
print(f"Reversed: {reversed_result}")

#

Original: [1, 2, 3, 4, 5, 6]
Reversed: [6, 5, 4, 3, 2, 1]


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 4 - Remove the First and Last Elements

def remove_first_last(lst):

  if len(lst) < 2:
    return[]

  return lst[1: -1]

my_list = [2, 4, 6, 8, 10]
result = remove_first_last(my_list)

print(f"Original: {my_list}")
print(f"Modified: {result}")

Original: [2, 4, 6, 8, 10]
Modified: [4, 6, 8]


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 5 - Get the First n Elements

def get_first_n(lst, n):
  return lst[:n]

original_list = [1, 2, 3, 4, 5, 6]
result = get_first_n(original_list, 4)

print(f"Original: {original_list}")
print(f"Extracted: {result}")

Original: [1, 2, 3, 4, 5, 6]
Extracted: [1, 2, 3, 4]


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 6 - Extract Elements from the End

def get_last_n(lst, n):
  return lst[-n:]

original_list = [1, 2, 3, 4, 5, 6]
result = get_last_n(original_list, 2)

print(f"Original: {original_list}")
print(f"Extracted: {result}")



Original: [1, 2, 3, 4, 5, 6]
Extracted: [5, 6]


In [ ]:
# 4.2 Exerice on List Manipulation
# Task 7 - Extract Elements in Reverse Order

def reverse_skip(lst):
  return lst[4::-2] #start at index 4, go till the 1st index

original_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(original_list)

print(f"Original: {original_list}")
print(f"Extracted: {result}")

Original: [1, 2, 3, 4, 5, 6]
Extracted: [5, 3, 1]


In [ ]:
# 4.3 Exercise on Nested List
# Task 1 - Flatted a Nested List

def flatten(lst):
  return  [item for sublist in lst for item in sublist]

nested_list = [[1,2], [3,4], [5]]
result = flatten(nested_list)

print(f"Original: {nested_list}")
print(f"Flattened: {result}")


Original: [[1, 2], [3, 4], [5]]
Flattened: [1, 2, 3, 4, 5]


In [ ]:
# 4.3 Exercise on Nested List
# Task 2 - Accessing Nested List Elements

def access_nested_element(lst, indices):
  current_element = lst

  try:
    for index in indices:
      current_element = current_element[index]
    return current_element
  except (IndexError, TypeError):
    return "Error: Invalid index path or element is not a list"

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
#path = [0,1]
result = access_nested_element(nested_list, [1,2])

print(f"Result: {result}")

Result: 6


In [ ]:
# 4.3 Exercise on Nested List
# Task 3 - Sum of All Elements in a Nested List

def sum_nested(lst):
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += sum_nested(item)
    else:
      total += item
  return total

nested_data = [1, [2, 3], [4, [5, 6]], 7]
result = sum_nested(nested_data)

print(f"Sum: {result}")

Sum: 28


In [ ]:
# 4.3 Exercise on Nested List
# Task 4 - Remove Specific Element from a Nested List

def remove_element(lst, elem):
  return [[item for item in sublist if item != elem] for sublist in lst]

input_list = [[1, 2], [3, 2], [4, 5]]
target = 2

result = remove_element(input_list, target)
print(f"Original: {input_list}")
print(f"Modified: {result}")


Original: [[1, 2], [3, 2], [4, 5]]
Modified: [[1], [3], [4, 5]]


In [ ]:
# 4.3 Exercise on Nested List
# Task 5 - Find the Maximum Element in a Nested List

def find_max(lst):
  current_max = None

  for item in lst:
    if isinstance(item, list):
      temp_max = find_max(item)
    else:
      temp_max = item

    if temp_max is not None:
      if current_max is None or temp_max > current_max:
        current_max = temp_max
  return current_max

input_list = [[1, 2], [3, 2], [4, 5]]
print(f"The maximum eement is: {find_max(input_list)}")

The maximum eement is: 5


In [ ]:
# 4.3 Exercise on Nested List
# Task 6 - Count Occurence of an Element in a Nested List

def count_occurrences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += count_occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

input_list = [[1, 2], [3, 4], [4,4]]
target = 4

result = count_occurrences(input_list, target)
print(f"The number of occurences of {target} is: {result}")

The number of occurences of 4 is: 3


In [ ]:
# 4.3 Exercise on Nested List
# Task 7 - Flatten a List of Lists of Lists

def deep_flatten(lst):
    """
    Recursively flattens a list with any depth of nesting.

    Parameters:
    lst (list): The nested list to flatten.

    Returns:
    list: A single-level list containing all elements.
    """
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            # If the item is a list, flatten it and add the results to our list
            flat_list.extend(deep_flatten(item))
        else:
            # If it's a single value, just append it
            flat_list.append(item)

    return flat_list

# Example usage:
input_data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(input_data)

print(f"Original: {input_data}")
print(f"Flattened: {result}")
# Output: [1, 2, 3, 4, 5, 6, 7, 8]

Original: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# 4.3 Exercise on Nested List
# Task 8 - Nested List Average

def average_nested(lst):
    """
    Calculates the average of all numeric elements in a nested list.

    Parameters:
    lst (list): A nested list containing numbers.

    Returns:
    float: The average of all elements.
    """
    def get_stats(data):
        total_sum = 0
        total_count = 0

        for item in data:
            if isinstance(item, list):
                # Recurse and add the results to current stats
                s, c = get_stats(item)
                total_sum += s
                total_count += c
            else:
                total_sum += item
                total_count += 1
        return total_sum, total_count

    total_sum, total_count = get_stats(lst)

    # Handle the case of an empty list to avoid ZeroDivisionError
    if total_count == 0:
        return 0

    return total_sum / total_count

# Example usage:
input_data = [[1, 2], [3, 4], [5, 6]]
result = average_nested(input_data)

print(f"The average is: {result}")

The average is: 3.6666666666666665


**10.1 Basic Vector and Matrix Operation with Numpy**

In [ ]:
# Problem 1 : Array Creation
# Q.N - 1

import numpy as np
array = np.zeros((2,2), dtype=int)
print("An empty array with size 2x2")
print(array)

An empty array with size 2x2
[[0 0]
 [0 0]]


In [ ]:
# Problem 1 : Array Creation
# Q.N - 2

import numpy as np
ones_array = np.ones((4,2), dtype=int)
print("An all one array with size 4x2")
print(ones_array)

An all one array with size 4x2
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# Problem 1 : Array Creation
# Q.N - 3

import numpy as np

filled_array = np.full((2), 5)
print("An array with given shape and type, filled with fill_value")
print(filled_array)

An array with given shape and type, filled with fill_value
[5 5]


In [ ]:
# Problem 1 : Array Creation
# Q.N - 4

import numpy as np
a = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
print("Original array:\n",a)

zeros_array = np.zeros_like(a, dtype=np.float64)
print("\nArray of zeros (float64):\n",zeros_array)


Original array:
 [[1 2 3]
 [4 5 6]]

Array of zeros (float64):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Problem 1 : Array Creation
# Q.N - 5

import numpy as np
a = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
print("Original array:\n",a)

ones_array = np.ones_like(a, dtype=np.float64)
print("\nArray of ones (float64):\n",zeros_array)


Original array:
 [[1 2 3]
 [4 5 6]]

Array of ones (float64):
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Problem 1 : Array Creation
# Q.N - 6

import numpy as np
new_list =[1,2,3,4]
print("Original List:\n",new_list)

new_array = np.array(new_list)
print("\nConverted Array:\n",new_array)


Original List:
 [1, 2, 3, 4]

Converted Array:
 [1 2 3 4]


In [2]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 1

import numpy as np

# array with values ranging 10 - 49
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 2

import numpy as np

# 3x3 matrix with values 0-8
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 3

import numpy as np

# 3x3 matrix
matrix = np.eye(3)

print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 4

import numpy as np

random_30 = np.random.random(30)

print(f"Array of size 30: {random_30}")
print("===============================")
print(f"Mean of random array: {random_30.mean()}")

Array of size 30: [0.77078262 0.21034832 0.13792418 0.598192   0.78179224 0.73659342
 0.23078735 0.88896621 0.43094909 0.69950647 0.53626848 0.52802165
 0.12973257 0.69867322 0.36634167 0.46292328 0.69108702 0.59997181
 0.46355383 0.05976782 0.58018082 0.67839521 0.83302509 0.07256526
 0.24629533 0.6052029  0.3309438  0.67978104 0.2998597  0.67559179]
Mean of random array: 0.500800806939781


In [13]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 5

import numpy as np

random_10 = np.random.random((10, 10))

print(f"Array of size 10x10: {random_10}")
print("===============================")
print(f"Max of random array: {random_30.max()}")
print(f"Min of random array: {random_30.min()}")

Array of size 10x10: [[0.23602959 0.9282849  0.80129554 0.247454   0.32044247 0.46157752
  0.97682734 0.0279737  0.02843602 0.43106596]
 [0.02954477 0.37778518 0.96617371 0.62215328 0.87050336 0.27027257
  0.95620714 0.05178197 0.97671647 0.65439702]
 [0.66615435 0.95583533 0.34104104 0.0700226  0.11064535 0.94600695
  0.68142472 0.19965542 0.58425675 0.18110621]
 [0.63325782 0.77900832 0.39462136 0.54887987 0.95579507 0.15010338
  0.18045568 0.91058343 0.59076024 0.40650422]
 [0.88405756 0.92482625 0.74059437 0.04676689 0.42521522 0.7053946
  0.91094229 0.89610493 0.58603567 0.91888069]
 [0.73087112 0.52133237 0.77798728 0.52865905 0.58515406 0.60819122
  0.46351721 0.43755916 0.79300644 0.57521701]
 [0.51059577 0.75633953 0.33124744 0.73854603 0.86207284 0.00575542
  0.25528211 0.82917589 0.21676831 0.87627464]
 [0.35697105 0.69437569 0.78462229 0.4172132  0.36533181 0.38069157
  0.44531949 0.30010236 0.81451188 0.39816013]
 [0.95148519 0.07790367 0.15740162 0.14477569 0.87751201 0.3

In [15]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 6

zeros_10 = np.zeros(10)

zeros_10[4] = 1

print("Zero array of size 10 - 5th element replaced by 1")
print(zeros_10)


Zero array of size 10 - 5th element replaced by 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 7

arr = [1,2,0,0,4,0]

reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1, 2, 0, 0, 4, 0]
Reversed array: [0, 4, 0, 0, 2, 1]


In [18]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 8

border_array = np.ones((5, 5))

border_array[1:-1, 1:-1] = 0
print("A 2D array with 1 or border and 0 inside")
print(border_array)

A 2D array with 1 or border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# Problem 2 : Array Manipulation : Numerical Ranges and Array Indexing
# Q.N - 9

checkboard_matrix = np.zeros((8,8))

checkboard_matrix[1::2, ::2] = 1
checkboard_matrix[::2, 1::2] = 1

print("A 8X8 matrix and fill it with a checkerboard pattern")
print(checkboard_matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [21]:
# Problem 3 : Array Operations

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [23]:
# Problem 3.1

xy_array = np.add(x,y)
print("Addition of two arrays X and Y")
print(xy_array)

vw_array = np.add(v,w)
print("Addition of two arrays V and W")
print(vw_array)



Addition of two arrays X and Y
[[ 6  8]
 [10 13]]
Addition of two arrays V and W
[20 22]


In [24]:
# Problem 3.2

xy_sub = np.subtract(x,y)
print("Subtraction of two arrays X and Y")
print(xy_sub)

vw_sub = np.subtract(v,w)
print("Subtraction of two arrays V and W")
print(vw_sub)

Subtraction of two arrays X and Y
[[-4 -4]
 [-4 -3]]
Subtraction of two arrays V and W
[-2 -2]


In [27]:
# Problem 3.3

x3_mul = np.multiply(x,3)
print("Multiplication of Array X with 3")
print(x3_mul)

v4_mul = np.multiply(v,4)
print("Multiplication of Array V with 4")
print(v4_mul)


Multiplication of Array X with 3
[[ 3  6]
 [ 9 15]]
Multiplication of Array V with 4
[36 40]


In [30]:
# Problem 3.4

sq_x = np.square(x)
print("Square of array X")
print(sq_x)
print()
sq_y = np.square(y)
print("Square of array Y")
print(sq_y)
print()
sq_v = np.square(v)
print("Square of array V")
print(sq_v)
print()
sq_w = np.square(w)
print("Square of array W")
print(sq_w)



Square of array X
[[ 1  4]
 [ 9 25]]

Square of array Y
[[25 36]
 [49 64]]

Square of array V
[ 81 100]

Square of array W
[121 144]


In [31]:
# Problem 3.5

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product: v(and)w: ", dot_vw)
print("Dot product: x(and)v: ", dot_xv)
print("Dot product: x(and)y: ", dot_xy)

Dot product: v(and)w:  219
Dot product: x(and)v:  [29 77]
Dot product: x(and)y:  [[19 22]
 [50 58]]


In [33]:
# Problem 3.6

concat_xy_row = np.concatenate((x, y), axis=0)

concat_vw_col = np.vstack((v, w))

print("Concatenate X,Y (Row): ")
print(concat_xy_row)
print("Concatenate V,W (Column): ")
print(concat_vw_col)



Concatenate X,Y (Row): 
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate V,W (Column): 
[[ 9 10]
 [11 12]]


In [36]:
# Problem 3.7

# 7. Concatenate x and v (Error Demonstration)
try:
    error_attempt = np.concatenate((x, v), axis=0)
except ValueError as e:
    explanation = str(e)

print("Explanation for x and v error:\n =>", explanation)

Explanation for x and v error:
 => all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [38]:
# Problem 4.1 : Matrix Operations

import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# --- 1. Prove A * A^-1 = I ---
A_inv = np.linalg.inv(A)
result_1 = np.dot(A, A_inv)
# We use allclose because floating point math might result in tiny values like 1e-16 instead of 0
proof_1 = np.allclose(result_1, np.eye(2))

# --- 2. Prove AB != BA ---
AB = np.dot(A, B)
BA = np.dot(B, A)
proof_2 = not np.array_equal(AB, BA)

# --- 3. Prove (AB)^T = B^T * A^T ---
AB_transpose = AB.T
BT_AT = np.dot(B.T, A.T)
proof_3 = np.allclose(AB_transpose, BT_AT)

# --- Output Results ---
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("-" * 30)
print("1. A * A^-1 Result:\n", result_1)
print(f"   Is it Identity? {proof_1}")
print("-" * 30)
print("2. AB:\n", AB)
print("   BA:\n", BA)
print(f"   Is AB != BA? {proof_2}")
print("-" * 30)
print("3. (AB)^T:\n", AB_transpose)
print("   B^T * A^T:\n", BT_AT)
print(f"   Is (AB)^T == B^T * A^T? {proof_3}")



Matrix A:
 [[3 4]
 [7 8]]

Matrix B:
 [[5 3]
 [2 1]]
------------------------------
1. A * A^-1 Result:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
   Is it Identity? True
------------------------------
2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   Is AB != BA? True
------------------------------
3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T * A^T:
 [[23 51]
 [13 29]]
   Is (AB)^T == B^T * A^T? True


In [39]:
# Problem 4.2 : Matrix Operations

import numpy as np

# Define coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Define constant matrix B
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Calculate the solution X = A_inv * B
X = np.dot(A_inv, B)

print(f"Solution: x = {X[0]}, y = {X[1]}, z = {X[2]}")

Solution: x = 2.0, y = 1.0, z = -2.0


In [ ]:
# Problem 4.3 : Matrix Operations

import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve using X = A^-1 * B
X = np.dot(np.linalg.inv(A), B)
print(X)